name: Update Lunch Feed

on:
  schedule:
    - cron: '0 8 * * 1-5'   # Weekdays 08:00 UTC
  workflow_dispatch:         # Manual trigger

permissions:
  contents: write  # Needed for pushing changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright feedgen
          playwright install --with-deps

      # 3️⃣ Generate RSS feed
      - name: Generate RSS feed
        run: python ./generate_feed.py

      # 4️⃣ Update README with today's menus in bullet points
      - name: Update README with today's menus
        run: |
          echo "# Lauttasaari Lunch Feed" > ./README.md
          echo "" >> ./README.md
          echo "Today's lunch menus (generated automatically):" >> ./README.md
          echo "" >> ./README.md
          echo "[![RSS Feed](https://img.shields.io/badge/RSS-Lounas%20Feed-orange)](https://bubbe404.github.io/lounas-feed/lounas_feed.xml)" >> ./README.md
          echo "" >> ./README.md
          python3 - <<'EOF'
import xml.etree.ElementTree as ET

rss_file = "./lounas_feed.xml"
tree = ET.parse(rss_file)
root = tree.getroot()
channel = root.find("channel")
items = channel.findall("item")

with open("README.md", "a", encoding="utf-8") as f:
    for item in items:
        title = item.find("title").text
        desc = item.find("description").text
        # Convert <br> to newlines and <b> tags to Markdown
        desc_md = desc.replace("<br>", "\n").replace("<b>", "**").replace("</b>", "**")
        # Split by lines and add bullets
        lines = desc_md.splitlines()
        f.write(f"## {title}\n\n")
        for line in lines:
            if line.strip():  # skip empty lines
                f.write(f"- {line.strip()}\n")
        f.write("\n")
EOF

      # 5️⃣ Commit and push updated feed & README
      - name: Commit and push updated feed & README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "LunchFeedBot"
          git config --global user.email "bot@example.com"

          git add ./lounas_feed.xml ./README.md
          git commit -m "Update feed and README $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
