name: Update Lunch Feed

on:
  schedule:
    - cron: '0 8 * * 1-5'   # Every weekday at 08:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 feedgen

      - name: Generate RSS feed
        run: python ./generate_feed.py

      - name: Commit and push updated feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "LunchFeedBot"
          git config --global user.email "bot@example.com"

          if [ -f ./lounas_feed.xml ]; then
            git add ./lounas_feed.xml README.md
            git commit -m "Update feed $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "No textual changes to commit"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
          else
            echo "❌ No lounas_feed.xml file found!"
            exit 1
