name: Update Lunch Feed

on:
  schedule:
    - cron: '0 8 * * 1-5'   # Weekdays at 08:00 UTC (~11:00 Helsinki)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright feedgen
          playwright install --with-deps

      - name: Generate RSS feed
        run: python ./generate_feed.py

      - name: Update README
        run: |
          echo "# Lauttasaari Lunch Feed" > README.md
          echo "" >> README.md
          echo "Today's lunch menus (generated automatically):" >> README.md
          echo "" >> README.md
          echo "[![RSS Feed](https://img.shields.io/badge/RSS-Lounas%20Feed-orange)](https://bubbe404.github.io/lounas-feed/lounas_feed.xml)" >> README.md
          echo "" >> README.md
          python3 -c "
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
rss_file = './lounas_feed.xml'
tree = ET.parse(rss_file)
root = tree.getroot()
channel = root.find('channel')
items = channel.findall('item')
with open('README.md', 'a', encoding='utf-8') as f:
    f.write(f'*(Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')})*\\n\\n')
    for item in items:
        title = item.find('title').text
        desc = (item.find('description').text or '').replace('<br>', '\\n').replace('<b>', '**').replace('</b>', '**')
        lines = desc.splitlines()
        f.write(f'## {title}\\n\\n')
        for line in lines:
            if line.strip():
                f.write(f'- {line.strip()}\\n')
        f.write('\\n')
"

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "LunchFeedBot"
          git config --global user.email "bot@example.com"
          git add README.md lounas_feed.xml
          git commit -m "Auto-update feed and README" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
