name: Update Lunch Feed

on:
  schedule:
    # Runs every weekday at 7:00 AM UTC (10:00 AM Helsinki)
    - cron: '0 7 * * 1-5'
  workflow_dispatch: # Manual trigger

jobs:
  build_feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Generate today's menu feed
        run: |
          python generate_feed.py

      - name: Commit and push updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add files only if they exist
          if [ -f "feed.xml" ]; then git add feed.xml; fi
          if [ -f "README.md" ]; then git add README.md; fi

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update lunch feed ($(date +'%Y-%m-%d'))"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi
