name: Update Lunch Feed

on:
  schedule:
    # Runs every weekday at 7:00 AM UTC (10:00 AM Helsinki)
    - cron: '0 7 * * 1-5'
  workflow_dispatch: # Manual trigger

jobs:
  build_feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Generate today's menu feed
        run: |
          python generate_feed.py

      - name: Commit and push if changes exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md feed.xml || true
          git diff --cached --quiet || git commit -m "Auto-update lunch feed"
          git push
