name: Update Lunch Feed

on:
  schedule:
    - cron: '0 8 * * 1-5'   # Every weekday at 08:00 UTC
  workflow_dispatch:         # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install playwright feedgen
          playwright install

      # 3️⃣ Run Python script to generate feed
      - name: Generate RSS feed
        run: python generate_feed.py

      # 4️⃣ Commit and push updated feed using GITHUB_TOKEN
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "LunchFeedBot"
          git config --global user.email "bot@example.com"
          git add lounas_feed.xml
          git commit -m "Update feed $(date)" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
